### ISSUE TITLE
How to send feedback?

### ISSUE THREAD

**Issue by guettli** [rbarrois/python-ldap#10]
The docs at https://pythonhosted.org/django-auth-ldap/
don't tell the user how to send you feedback.

Please tell us.

**Comment by rbarrois** [comment]
This is a `python-ldap` fork that adds Py3 support; it has no relation to django-auth-ldap.

According to PyPI (https://pypi.python.org/pypi/django-auth-ldap/1.2.6), the upstream of django-auth-ldap is at http://bitbucket.org/psagers/django-auth-ldap/.
