### ISSUE TITLE
pip install django-auth-ldap pulls in Django-1.8.2. We want to keep Django 1.6

### ISSUE THREAD

**Issue by guettli** [rbarrois/python-ldap#12]
If I try to update django-auth-ldap pip install a new version of Django.

Do you have a idea why pip pulls in a new version?

I tried to find the reasons, but could not find it.

We want to keep Django 1.6 for the next weeks.

**Comment by rbarrois** [comment]
Hello,

I don't maintain `django-auth-ldap`; I can't help you there.
Have you looked at `django-auth-ldap`'s `setup.py`?

**Comment by guettli** [comment]
thank you for your fast reply!
