### ISSUE TITLE
Merge Python 3 branch into main branch

### ISSUE THREAD

**Issue by mcarans** [rbarrois/python-ldap#6]
It would be good if there was just a single branch that supports both Python 2 and 3 and for which binary packages (ideally whl files) are made for both Python 2 and 3 on Windows and UNIX (and put on the pypi repository).

**Comment by rbarrois** [comment]
Hi,

The `py3` branch is compatible with both Py2 and Py3.

I hoped to get it merged upstream, but haven't had any success so far.
If I can't get it merged within a month, I'll fork the project altogether and provide it on PyPI with a separate name (likely `pyldap`).

However, I can confirm that the `py3` branch works properly: I've been using it in production for more than a year!

Feel free to ping me back in a few weeks :)

**Comment by aaugustin** [comment]
Yes, having a package available on PyPI would be nice, at least to speed up deploys.

**Comment by rkuska** [comment]
Ping.
Hi Raphael,
does it seem that upstream will merge your fork? Or will you release it on PyPI by yourself?

**Comment by aaugustin** [comment]
Upstream has been unresponsive for 18 months.

**Comment by rkuska** [comment]
And how does it look like with releasing on PyPI and active maintenance?

**Comment by rbarrois** [comment]
@rkuska Basically, the current situation is:
- Upstream doesn't seem interested in merging my changes (asked three times, no answer)
- Distributing this Py3-compatible version on PyPI has been on my todo list for a few months (would be under the `pyldap` name, I think)
- I don't have much time for maintaining more than "the Py3 compatibility layer" at the moment
- The source code licensing is rather unclear, e.g distributed under "A pythonic license" (See https://mail.python.org/pipermail/python-ldap/2014q2/003374.html)

So:
- If upstream shows interest, I'd be more than happy to help integrating
- If one or two other users are ready to help with maintenance, I can find a few hours to properly setup / document / cleanup this fork and make it "production ready".

**Comment by encukou** [comment]
Hello,

Here is Michael Ströder's response to the patchset: https://mail.python.org/pipermail/python-ldap/2013q4/003311.html
He didn't get an answer; it seems he thinks the communication problem is at this side.

**Comment by hroncok** [comment]
Hi @rbarrois,

I'm willing to help you with maintenance. I created a pyldap Github organization with [pyldap repo](https://github.com/pyldap/pyldap) (contains your patches rebased by @tiran). I saw pyldap on PyPI is registered by xelnor, is that you?

I would like to give it some love and hopefully release a version on PyPI soon.

**Comment by ddriddle** [comment]
@rbarrois I am also willing to help with maintenance and development. Any chance that this fork can still be merged back into upstream? If there is any development work I can help with to help move this project forward I am definitely willing to help.

**Comment by rbarrois** [comment]
Awesome!

I'll try to bring the pyldap version up to speed; I suggest to move the conversation over there.
Hopefully, we can converge on a version that can be merged back into upstream's python-ldap — maybe modernizing its tooling in the process!

@hroncok yes, I'm xelnor on PyPI

**Comment by rbarrois** [comment]
This has now moved to the https://github.com/pyldap/pyldap project :)
